name: Deploy con Docker

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Configuración Docker CORREGIDA (pasos separados)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Run docker-compose
        run: |
          docker-compose build --no-cache
          docker-compose up -d
